### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by majuntao** [unidal/maven-plugins#2] opened 2015-07-14 03:18 UTC
hi guys,

I download the latest master release , when compile it with 'mvn compile' , got a prompt that
 "Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.2.0 or one of its dependencies could not be resolved: Failure to find org.unidal.maven.plugins:codegen-maven-plugin:jar:2.2.0 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]"

does anyone have any idea? 

thanks very much!!

**Comment by majuntao** [comment] 2015-07-14 08:38
for item project-maven-plugin and plexus-maven-plugin.
change the reference from 2.2.0 to 2.2.2.
<dependency>
         <groupId>org.unidal.maven.plugins</groupId>
         <artifactId>codegen</artifactId>
         <version>2.2.2</version>
      </dependency>

compile pass.

**Comment by jialinsun** [comment] 2015-10-29 03:21
I have met similar problem,when i run mvn compile in the root directory, errors occur as belows:

Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.unidal.maven.plugins:codegen-maven-plugin:pom:2.2.0 from/to maven-plugins (https://raw.githubusercontent.com/unidal/maven-plugins/mvn-repo): peer not authenticated
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239) 
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 28 more

**Comment by qmwu2000** [comment] 2016-03-07 00:10
It's fixed now, please check it out

**Closed by qmwu2000** 2016-03-07 00:10 UTC
